version: '1'

services:
  downscale_pod:
    build: ./downscale_pod
    volumes:
      - ./ressources:/app/ressources
      - ./results:/app/results
      - ./tmp:/app/tmp

  langident_pod:
    build: ./langident_pod
    volumes:
      - ./ressources:/app/ressources
      - ./results:/app/results
      - ./tmp:/app/tmp
    depends_on:
      - downscale_pod
  
  subtitle_pod:
    build: ./subtitle_pod
    volumes:
      - ./ressources:/app/ressources
      - ./results:/app/results
      - ./tmp:/app/tmp
    depends_on:
      - langident_pod
  
  animal_detect_pod:
    build: ./animal_detect_pod
    volumes:
      - ./ressources:/app/ressources
      - ./results:/app/results
      - ./tmp:/app/tmp
    depends_on:
      - subtitle_pod


